### ISSUE TITLE
Add Travis-CI support

### ISSUE THREAD

**Issue by PeteHaitch** [kasperdanielhansen/bsseq#5]
I'm working on this. Email from Kasper: 

> What I would really need is for any pull request to be checked up against Bioc-devel with Bioc-devel packages and the right version of R for Bioc-devel.  And then I would want to be able for the submitter and myself and possibly others to see the result of R CMD check on the pull request.

**Comment by PeteHaitch** [comment]
Some notes on the process:

- Starting with `.travis.yml` from https://github.com/PeteHaitch/GenomicTuples

- First glitch, bsseq uses pdf vignette from `.Rnw`.

**Comment by PeteHaitch** [comment]
Travis now supports Docker containers (http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/). This is reason to get excited according to @craigcitro, the original developer of r-travis https://twitter.com/craigcitro/status/634073716691898368
Perhaps we can lead a push to develop a Travis setup for use with the BioC Docker containers (http://bioconductor.org/help/docker/)?

**Comment by craigcitro** [comment]
:+1: I suspect @jimhester will be interested...

**Comment by jimhester** [comment]
The docker support should make this much more straightforward.

These docker commands work when testing on my local machine but I have not yet tested on travis

```yaml
sudo: required

language: c

services:
  - docker

before_install:
  - docker pull bioconductor/devel_base
  - docker run -d --name devel -v $(pwd -P):/mnt bioconductor/devel_base
  - docker exec devel Rscript -e 'install.packages("devtools")'

script:
  # install package dependencies and BiocCheck
  - docker exec devel /bin/sh -c "cd /mnt;Rscript -e 'options(repos=BiocInstaller::biocinstallRepos());devtools::install_deps(dep=T);install.packages(\"BiocCheck\")'"
  # build package
  - docker exec devel /bin/sh -c "cd /mnt;R CMD check *tar.gz"
  # check package
  - docker exec devel /bin/sh -c "cd /mnt;R CMD check *tar.gz"
  # BiocCheck package
  - docker exec devel /bin/sh -c "cd /mnt;R CMD BiocCheck *tar.gz"
```

I also recently submitted https://github.com/hadley/devtools/pull/895, which will automatically use repos set from `BiocInstaller::biocinstallRepos()` if the package being installed is a Bioconductor package, so we won't have to special case them ala [r-builder/pkg-build.sh#L60-L63](https://github.com/metacran/r-builder/blob/dbda6bbaead88eb948044bf5d9e0545ce6880d57/pkg-build.sh#L60-L63), [travis-ci/travis-build/lib/travis/build/script/r.rb#L277](https://github.com/travis-ci/travis-build/blob/35a436fe4188ec0ca5c9441981d88eebab3a339b/lib/travis/build/script/r.rb#L277) or above.

Right now the Bioconductor docker images are based on `rocker/rstudio`, which includes Rstudio server, but does not include devtools.  As you don't need Rstudio server but do need devtools in a Travis image I will talk to @dtenenba and see if we can supply images that would be more tailored to use in Travis (or other CIs).

Obviously the above is not as nice as the native integration or r-builder, but it is a proof of concept using docker at least.

I am a little unclear if the commands in `-script` need to be docker commands or if all the commands there are automatically run in docker, also unclear if the repository to be checked is automatically mounted.  Travis' documentation on this feature is sparse.
